// Generated by CoffeeScript 1.9.1
(function() {
  var draggable, dropTarget, jodaDateToHumanReadable, otcRepStatusToHumanReadable;

  jodaDateToHumanReadable = function(jodaDate) {
    var dt;
    dt = new Date(jodaDate);
    return dt.getFullYear() + "-" + (dt.getMonth() + 1) + "-" + dt.getDate();
  };

  otcRepStatusToHumanReadable = function(status) {
    var js;
    js = JSON.parse(status);
    js.startDate = jodaDateToHumanReadable(js.startDate);
    js.endDate = jodaDateToHumanReadable(js.endDate);
    js.dateStored = jodaDateToHumanReadable(js.dateStored);
    return js;
  };

  draggable = function() {
    return {
      restrict: "A",
      link: function(scope, element, attributes, ctlr) {
        element.attr("draggable", true);
        return element.bind("dragstart", function(e) {
          return e.originalEvent.dataTransfer.setData("text", attributes.itemid);
        });
      }
    };
  };

  dropTarget = function() {
    return {
      restrict: "A",
      link: function(scope, element, attributes, ctlr) {
        element.bind("dragover", function(e) {
          return e.preventDefault();
        });
        return element.bind("drop", function(e) {
          scope.moveToBox(parseInt(e.originalEvent.dataTransfer.getData("text")));
          return e.preventDefault();
        });
      }
    };
  };

}).call(this);
